spring:
  data:
    mongodb:
      database: brewfantasy
      port: 27017
      uri: mongodb://ec2-44-209-166-240.compute-1.amazonaws.com:27017
  application:
    name: BEER
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka




